services:
  homewakeword:
    container_name: homewakeword
    image: local/homewakeword
    restart: unless-stopped
    ports:
      - "0.0.0.0:10700:10700"
    networks:
      - bridge-network
    volumes:
      - /opt/homewake/data:/data
      - /opt/homewake/share:/share
    command: ["serve", "--host", "0.0.0.0", "--port", "10700"]

networks:
  bridge-network:
    external: true
