services:
  homewakeword:
    container_name: homewakeword-bcresnet
    image: local/homewakeword-bcresnet
    restart: unless-stopped
    ports:
      - "0.0.0.0:10700:10700"
    networks:
      - bridge-network
    volumes:
      - /opt/homewake/data:/data
      - /opt/homewake/share:/share
    command: ["serve"]

networks:
  bridge-network:
    external: true
